call plug#begin('~/.vim/plugged')

Plug 'code-stats/code-stats-vim.git'
Plug 'vim-airline/vim-airline'

call plug#end()
let g:codestats_api_key = ${CODESTATS_KEY}
let g:airline_section_x = airline#section#create_right(['tagbar', 'filetype', '%{CodeStatsXp()}'])

